### PR TITLE
chore: update env configuration for development

### PR DESCRIPTION
**Pull request by phucledien**
## What's this PR do?

- [x] update configuration env for dev and release
- [x] add gitignore
- [x] update readme for config env

### CODE REVIEW

**Comment by pketh** [comment]
code looks good, but I'm sure aligned on the reason behind the goals of: 
`update configuration env for dev and release` and `update readme for config env`, because we don't have secrets in there, we don't need the extra complexity of dev/release env

**Comment by pketh** [comment]
generally speaking, for code like this that will be very infrequently updated (because it's just a thin shell around the web app) I think the primary goal should be simplicity and high maintainability - even/especially at the cost of sophistication

**Comment by phucledien** [comment]
> code looks good, but I'm sure aligned on the reason behind the goals of: `update configuration env for dev and release` and `update readme for config env`, because we don't have secrets in there, we don't need the extra complexity of dev/release env

Sorry if this pr is confusing.
To give more context. When other developers try to build u guy's project, they have to change the team, and bundle ID setting, from your team (VWRQY6FSN5, club.kinopio.app) to theirs, since we are not in u guys Apple development team. So I just split it into the own cfg file, so that people can easily change the teamID and bundle ID without affecting the source itself.

But as you said, If you think it makes the source more complex, please close the PR. Thank you 🙏

**Comment by pketh** [comment]
oic that makes sense, 
in that case can we move the extra config vars into the existing `Config.xcconfig` file and remove the .template file step?

**Comment by pketh** [comment]
tried to build this and got the error `../kinopio-apple/Kinopio.xcconfig:1:1 unable to open configuration settings file`

**Comment by pketh** [comment]
> oic that makes sense, in that case can we move the extra config vars into the existing `Config.xcconfig` file and remove the .template file step?

ok did that and now, confirmed that everything builds/runs, and now i'm merging it in

thx!

**Pull request merged**
